export const PATH_HOME = '/'
export const PATH_INDEX = 'inicio'
export const PATH_ROLE_ADMIN = 'admin'
export const PATH_ROLE_STUDENT = 'student'
export const PATH_DASHBOARD =
  '/' + import.meta.env.VITE_INITIAL_ACTIVITY_ID + '/dashboard'
export const PATH_CONSOLE = 'console'
export const PATH_APPS = 'services'
export const PATH_SETTING = 'settings'
export const PATH_LOGIN = '/login'
export const PATH_RESET_PASSWORD = '/reset_password'
export const PATH_CHANGE_PASSWORD = `${PATH_RESET_PASSWORD}/:token`
export const PATH_STUDENTS = 'students'
export const PATH_REQUESTS = 'requests'
export const PATH_PERSON_FORM = 'people/:action/:personId?'

// external routes
export const BASE_API_PATH = import.meta.env?.VITE_APP_API_SERVICE_URL
export const API_PATH_GET_REPOSITORIES = '/repositories'
export const API_PATH_CLONE_REPOSITORY = '/repositories/clone'
export const API_PATH_GET_TAG_LIST = '/get_tags/'
export const API_PATH_CHECKOUT = '/checkout'
export const API_PATH_LOGIN = '/login'
export const API_PATH_GET_USER_MENU_OPTION = '/menu_options/'
export const API_PATH_CREATE_UPDATE_MENU_OPTION = '/menu_options'
export const API_GET_STAFF_PAGINATION = '/staff/pagination'
export const API_PATH_CREATE_UPDATE_STAFF = '/staff'
export const API_PATH_GET_USER_PAGINATION = '/user/pagination'
export const API_PATH_CREATE_UPDATE_PERSON = '/person'
export const API_PATH_GET_ONE_PERSON = '/person/'
export const API_PATH_GET_PEOPLE_PAGINATION = '/person/pagination'
export const API_PATH_GET_ROLE_PAGINATION = '/role/pagination'
export const API_PATH_CREATE_UPDATE_USER = '/user'
export const API_PATH_REQUEST_RESET_PASSWORD = '/request_password_reset'
export const API_PATH_RESET_PASSWORD = '/reset_password'
export const API_PATH_CHANGE_PASSWORD = '/user/change_password'
export const API_PATH_CREATE_UPDATE_STUDENT = '/students'
export const API_PATH_GET_STUDENT_PAGINATION = '/students/pagination'
export const API_PATH_CREATE_UPDATE_ROLE = '/role'
export const API_PATH_GET_ONE_ROLE = '/role/'
export const API_PATH_GET_MENU_OPTIONS_WITH_PERMISSIONS =
  '/menu_options/get_with_permission'
export const API_PATH_GET_CATALOG_PAGINATION = '/catalogs/pagination'
export const API_PATH_CREATE_UPDATE_CATALOG = '/catalogs'
export const API_PATH_GET_CATALOG_ITEMS = '/catalogs/:key/items'
export const API_PATH_GET_ACTIVITY_PARAMETER = '/parameter/'
export const API_PATH_GET_PARAMETER_PAGINATION = '/parameter/pagination'
export const API_PATH_CREATE_UPDATE_PARAMETER = '/parameter'
export const API_PATH_UPDATE_CATALOG_ITEM = '/catalogs/:catalogId/items/:itemId'
export const PATH_GET_CATALOG = '/catalog/'
export const API_PATH_GET_CATALOG_LIST = '/catalog/multi_list'
export const API_PATH_CREATE_PERSON_REFERENCES = '/person/references'
export const API_PATH_GET_REQUEST_PAGINATION = '/requests/pagination'
export const API_PATH_CREATE_UPDATE_REQUEST = '/requests'
export const API_PATH_CREATE_UPDATE_NOTIFICATION_TEMPLATE =
  '/notification_templates'
export const API_PATH_GET_NOTIFICATION_TEMPLATE_PAGINATION =
  '/notification_templates/pagination'
export const API_PATH_GET_NOTIFICATION_TEMPLATE = '/notification_templates'
export const API_PATH_CREATE_UPDATE_NOTIFICATION = '/notifications'
export const API_PATH_GET_NOTIFICATION_PAGINATION = '/notifications/pagination'
export const API_PATH_GET_NOTIFICATION = '/notifications'
export const API_PATH_CREATE_UPDATE_APPOINTMENT = '/appointments'
export const API_PATH_GET_APPOINTMENT_PAGINATION = '/appointments/pagination'
export const API_PATH_GET_APPOINTMENT = '/appointments'
export const API_PATH_CREATE_UPDATE_FOLLOW_UP = '/follow_ups'
export const API_PATH_GET_FOLLOW_UP_PAGINATION = '/follow_ups/pagination'
export const API_PATH_GET_FOLLOW_UP = '/follow_ups'
export const API_PATH_CREATE_UPDATE_STUDENT_DOCUMENT = '/student_documents'
export const API_PATH_GET_STUDENT_DOCUMENT_PAGINATION =
  '/student_documents/pagination'
export const API_PATH_GET_STUDENT_DOCUMENT = '/student_documents'

export const API_PATH_GET_DASHBOARD_METRICS = '/dashboard/metrics'
export const API_PATH_GET_DASHBOARD_ACTIVITY = '/dashboard/activity'
export const API_PATH_CREATE_UPDATE_SCHOLARSHIP = '/scholarships'
export const API_PATH_GET_SCHOLARSHIP_PAGINATION = '/scholarships/pagination'
export const API_PATH_GET_SCHOLARSHIP = '/scholarships'
export const API_PATH_CREATE_UPDATE_DISBURSEMENT = '/disbursements'
export const API_PATH_GET_DISBURSEMENT_PAGINATION =
  '/disbursements/pagination'
export const API_PATH_GET_DISBURSEMENT = '/disbursements'
export const API_PATH_CREATE_UPDATE_SPONSOR = '/sponsors'
export const API_PATH_GET_SPONSOR_PAGINATION = '/sponsors/pagination'
export const API_PATH_GET_SPONSOR = '/sponsors'
export const API_PATH_CREATE_UPDATE_PLEDGE = '/pledges'
export const API_PATH_GET_PLEDGE_PAGINATION = '/pledges/pagination'
export const API_PATH_GET_PLEDGE = '/pledges'
export const API_PATH_CREATE_UPDATE_SCHOLARSHIP_COST = '/scholarship_costs'
export const API_PATH_GET_SCHOLARSHIP_COST_PAGINATION =
  '/scholarship_costs/pagination'
export const API_PATH_GET_SCHOLARSHIP_COST = '/scholarship_costs'
export const API_PATH_CREATE_UPDATE_REQUIREMENT = '/requirements'
export const API_PATH_GET_REQUIREMENT_PAGINATION = '/requirements/pagination'
export const API_PATH_GET_REQUIREMENT = '/requirements'
export const API_PATH_CREATE_UPDATE_STUDENT_REQUIREMENT =
  '/student_requirements'
export const API_PATH_GET_STUDENT_REQUIREMENT_PAGINATION =
  '/student_requirements/pagination'
export const API_PATH_GET_STUDENT_REQUIREMENT = '/student_requirements'

// Calificaciones / Índice académico
export const API_PATH_CREATE_UPDATE_TERM = '/grades/terms'
export const API_PATH_GET_TERM_PAGINATION = '/grades/terms/pagination'
export const API_PATH_GET_TERM = '/grades/terms'
export const API_PATH_GET_TERM_BY_STUDENT = '/grades/terms/student'

// Actividades / voluntariado
export const API_PATH_CREATE_UPDATE_ACTIVITY = '/activities'
export const API_PATH_GET_ACTIVITY = '/activities'
export const API_PATH_GET_ACTIVITY_PAGINATION = '/activities/pagination'
export const API_PATH_ACTIVITY_ENROLL = '/activities/enroll'
export const API_PATH_ACTIVITY_PARTICIPANT_UPDATE =
  '/activities/participants/status'
